package my.mgw.dianaccount.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import my.mgw.dianaccount.model.Bill;
import my.mgw.dianaccount.model.Category;

import my.mgw.dianaccount.greendao.BillDao;
import my.mgw.dianaccount.greendao.CategoryDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig billDaoConfig;
    private final DaoConfig categoryDaoConfig;

    private final BillDao billDao;
    private final CategoryDao categoryDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        billDaoConfig = daoConfigMap.get(BillDao.class).clone();
        billDaoConfig.initIdentityScope(type);

        categoryDaoConfig = daoConfigMap.get(CategoryDao.class).clone();
        categoryDaoConfig.initIdentityScope(type);

        billDao = new BillDao(billDaoConfig, this);
        categoryDao = new CategoryDao(categoryDaoConfig, this);

        registerDao(Bill.class, billDao);
        registerDao(Category.class, categoryDao);
    }
    
    public void clear() {
        billDaoConfig.clearIdentityScope();
        categoryDaoConfig.clearIdentityScope();
    }

    public BillDao getBillDao() {
        return billDao;
    }

    public CategoryDao getCategoryDao() {
        return categoryDao;
    }

}
